#!/usr/bin/env bash
# generate_system_report.sh — Generate SYSTEM.md with hardware/software details
# for AMD Ryzen AI development on Linux.
#
# Copyright (c) 2023 Advanced Micro Devices, Inc. All rights reserved.
# MIT License (see LICENSE.txt)
#
# Usage: ./generate_system_report.sh [--no-sudo] [--output <path>] [--help]

set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUTPUT_FILE="${SCRIPT_DIR}/SYSTEM.md"
REPORT_VERSION="1.2.0"
NO_SUDO="false"
SUDO_AVAILABLE="false"
REPORT=""

# NPU device ID → generation mapping
declare -A NPU_DEVICE_MAP=(
    ["1502:00"]="PHX/HPT (AIE2)"
    ["17f0:00"]="STX (AIE2P)"
    ["17f0:10"]="STX (AIE2P)"
    ["17f0:11"]="Strix Halo (AIE2P)"
    ["17f0:20"]="KRK (AIE2P)"
)

# Summary tracking
declare -A SUMMARY_STATUS
declare -A SUMMARY_DETAIL

# Colors
BOLD="\033[1m"
DIM="\033[2m"
RED="\033[31m"
GREEN="\033[32m"
YELLOW="\033[33m"
CYAN="\033[36m"
RESET="\033[0m"

# ---------------------------------------------------------------------------
# Utility functions
# ---------------------------------------------------------------------------

cmd_exists() { command -v "$1" &>/dev/null; }

try_sudo() {
    if [[ "$SUDO_AVAILABLE" == "true" ]]; then
        sudo "$@" 2>/dev/null
    else
        return 1
    fi
}

log_section() { printf "${BOLD}${CYAN}[*] %s${RESET}\n" "$1"; }
log_ok()      { printf "  ${GREEN}[OK]${RESET}   %s\n" "$1"; }
log_warn()    { printf "  ${YELLOW}[WARN]${RESET} %s\n" "$1"; }
log_fail()    { printf "  ${RED}[FAIL]${RESET} %s\n" "$1"; }

md() { REPORT+="$1"$'\n'; }

init_sudo() {
    if [[ "$NO_SUDO" == "true" ]]; then
        SUDO_AVAILABLE="false"
        log_warn "Sudo disabled (--no-sudo). Some info will be limited."
        return
    fi
    printf "${YELLOW}Some commands (dmidecode, dmesg) need sudo for enhanced info.${RESET}\n"
    printf "Attempt sudo? [Y/n] "
    read -r response
    if [[ "$response" =~ ^[Nn] ]]; then
        SUDO_AVAILABLE="false"
        log_warn "Skipping privileged commands."
    else
        if sudo -v 2>/dev/null; then
            SUDO_AVAILABLE="true"
            log_ok "Sudo authenticated."
        else
            SUDO_AVAILABLE="false"
            log_warn "Sudo authentication failed. Continuing without elevated privileges."
        fi
    fi
}

parse_args() {
    while [[ $# -gt 0 ]]; do
        case "$1" in
            --no-sudo)  NO_SUDO="true"; shift ;;
            --output)   OUTPUT_FILE="$2"; shift 2 ;;
            --help|-h)
                echo "Usage: $0 [--no-sudo] [--output <path>] [--help]"
                echo ""
                echo "Generate SYSTEM.md with hardware/software details for AMD Ryzen AI."
                echo ""
                echo "Options:"
                echo "  --no-sudo    Skip privileged commands (dmidecode, dmesg)"
                echo "  --output     Output file path (default: SYSTEM.md in script directory)"
                echo "  --help       Show this message"
                exit 0
                ;;
            *) echo "Unknown option: $1"; exit 1 ;;
        esac
    done
}

# Helper: extract value from lscpu output
lscpu_val() {
    echo "$LSCPU_OUTPUT" | grep -m1 "^$1:" | sed "s/^$1:[[:space:]]*//"
}

# ---------------------------------------------------------------------------
# Section: Header
# ---------------------------------------------------------------------------

section_header() {
    local gen_date
    gen_date="$(date -u +"%Y-%m-%d %H:%M:%S %Z")"
    local host
    host="$(hostname 2>/dev/null || echo "unknown")"

    md "# System Report"
    md ""
    md "> Auto-generated by \`generate_system_report.sh\` v${REPORT_VERSION}"
    md "> Date: ${gen_date}  |  Host: ${host}"
    md ""
}

# ---------------------------------------------------------------------------
# Section: System Overview
# ---------------------------------------------------------------------------

section_system_overview() {
    log_section "System Overview"

    local os_name="" os_version="" kernel="" arch="" uptime_str=""

    if [[ -f /etc/os-release ]]; then
        os_name="$(. /etc/os-release && echo "${PRETTY_NAME:-${NAME} ${VERSION}}")"
    fi
    kernel="$(uname -r 2>/dev/null || echo "N/A")"
    arch="$(uname -m 2>/dev/null || echo "N/A")"
    if cmd_exists uptime; then
        uptime_str="$(uptime -p 2>/dev/null || echo "N/A")"
    fi

    # Linux firmware version (critical for ROCm stability on gfx1151)
    local linux_fw_ver=""
    if [[ -f /usr/lib/firmware/updates/amdgpu/VERSION ]]; then
        linux_fw_ver="$(cat /usr/lib/firmware/updates/amdgpu/VERSION 2>/dev/null || true)"
    fi
    if [[ -z "$linux_fw_ver" ]] && cmd_exists dnf; then
        linux_fw_ver="$(rpm -q linux-firmware 2>/dev/null | sed 's/linux-firmware-//' || true)"
    elif [[ -z "$linux_fw_ver" ]] && cmd_exists dpkg; then
        linux_fw_ver="$(dpkg -s linux-firmware 2>/dev/null | grep "^Version:" | awk '{print $2}' || true)"
    fi

    log_ok "${os_name} / ${kernel}"

    md "---"
    md ""
    md "## System Overview"
    md ""
    md "| Field | Value |"
    md "|-------|-------|"
    md "| **OS** | ${os_name} |"
    md "| **Kernel** | ${kernel} |"
    md "| **Architecture** | ${arch} |"
    md "| **Hostname** | $(hostname 2>/dev/null || echo "N/A") |"
    md "| **Uptime** | ${uptime_str} |"
    [[ -n "$linux_fw_ver" ]] && md "| **Linux Firmware** | ${linux_fw_ver} |"
    md ""

    # Kernel compatibility assessment
    md "### Kernel Compatibility"
    md ""

    local kver_major kver_minor kver_patch
    kver_major="$(echo "$kernel" | cut -d. -f1)"
    kver_minor="$(echo "$kernel" | cut -d. -f2)"
    kver_patch="$(echo "$kernel" | cut -d. -f3 | cut -d- -f1)"

    local kernel_issues=()

    # Check for amdxdna IOMMU SVA regression (6.18.0 - 6.18.7)
    if [[ "$kver_major" -eq 6 && "$kver_minor" -eq 18 && "$kver_patch" -le 7 ]]; then
        kernel_issues+=("IOMMU SVA regression breaks amdxdna NPU driver (6.18.0-6.18.7). Upgrade to 6.19.2+.")
    fi
    # Check for amdxdna firmware protocol incompatibility (6.18.8)
    if [[ "$kver_major" -eq 6 && "$kver_minor" -eq 18 && "$kver_patch" -eq 8 ]]; then
        kernel_issues+=("Firmware protocol incompatibility in 6.18.8 for amdxdna. Upgrade to 6.19.2+.")
    fi

    # Check amdgpu kernel cmdline parameters
    local cmdline
    cmdline="$(cat /proc/cmdline 2>/dev/null || true)"
    local cwsr_status="not set (default)"
    if echo "$cmdline" | grep -q "amdgpu.cwsr_enable=0"; then
        cwsr_status="disabled (amdgpu.cwsr_enable=0)"
    elif echo "$cmdline" | grep -q "amdgpu.cwsr_enable=1"; then
        cwsr_status="enabled (amdgpu.cwsr_enable=1)"
    fi

    if [[ ${#kernel_issues[@]} -gt 0 ]]; then
        md "| Issue | Details |"
        md "|-------|---------|"
        for issue in "${kernel_issues[@]}"; do
            md "| **WARNING** | ${issue} |"
            log_warn "Kernel: ${issue}"
        done
        md ""
        SUMMARY_STATUS["Kernel"]="WARN"
        SUMMARY_DETAIL["Kernel"]="${kernel} — known issues"
    else
        md "No known kernel compatibility issues detected."
        md ""
        SUMMARY_STATUS["Kernel"]="OK"
        SUMMARY_DETAIL["Kernel"]="${kernel}"
    fi

    # Kernel upgrade availability
    md "### Available Kernel Updates"
    md ""
    local avail_kernels=""
    local target_kernel_available="false"
    if cmd_exists dnf; then
        avail_kernels="$(timeout 15 dnf check-update kernel 2>/dev/null | grep -E '^kernel\.' || true)"
    elif cmd_exists apt; then
        avail_kernels="$(timeout 15 apt list --upgradable 2>/dev/null | grep -i '^linux-image' || true)"
    fi

    if [[ -n "$avail_kernels" ]]; then
        md "| Package | Version | Repository |"
        md "|---------|---------|------------|"
        while IFS= read -r line; do
            [[ -z "$line" ]] && continue
            local pkg ver repo
            pkg="$(echo "$line" | awk '{print $1}')"
            ver="$(echo "$line" | awk '{print $2}')"
            repo="$(echo "$line" | awk '{print $3}')"
            md "| ${pkg} | ${ver} | ${repo} |"
            # Check if target kernel (6.19.2+) is available
            local avail_major avail_minor avail_patch
            avail_major="$(echo "$ver" | cut -d. -f1)"
            avail_minor="$(echo "$ver" | cut -d. -f2)"
            avail_patch="$(echo "$ver" | cut -d. -f3 | cut -d- -f1)"
            if [[ "$avail_major" -ge 7 ]] 2>/dev/null || \
               [[ "$avail_major" -eq 6 && "$avail_minor" -gt 19 ]] 2>/dev/null || \
               [[ "$avail_major" -eq 6 && "$avail_minor" -eq 19 && "$avail_patch" -ge 2 ]] 2>/dev/null; then
                target_kernel_available="true"
            fi
        done <<< "$avail_kernels"
        md ""

        if [[ "$target_kernel_available" == "true" ]]; then
            md "> **Target kernel 6.19.2+ is available.** Upgrade with \`sudo dnf upgrade kernel\` to unblock NPU."
            log_ok "Kernel 6.19.2+ available for upgrade"
            # Augment summary if current kernel has issues
            if [[ "${SUMMARY_STATUS[Kernel]}" == "WARN" ]]; then
                SUMMARY_DETAIL["Kernel"]="${SUMMARY_DETAIL[Kernel]} — 6.19.2+ available"
            fi
        else
            md "> Available kernel update does not meet the 6.19.2+ target for NPU support."
            log_warn "Available kernel update does not meet 6.19.2+ target"
        fi
        md ""
    else
        md "No kernel updates available (system is up to date or package manager not accessible)."
        md ""
        log_ok "No kernel updates pending"
    fi

    md "| Parameter | Value |"
    md "|-----------|-------|"
    md "| **amdgpu CWSR** | ${cwsr_status} |"
    md ""

    # Disk Space
    md "### Disk Space"
    md ""
    md "| Mount | Filesystem | Size | Used | Available | Use% |"
    md "|-------|-----------|------|------|-----------|------|"

    local mount_points=("/" "/home" "/tmp")
    for model_dir in /opt/models /data; do
        [[ -d "$model_dir" ]] && mount_points+=("$model_dir")
    done

    local seen_devs=()
    local disk_warn="false"
    for mp in "${mount_points[@]}"; do
        if [[ -d "$mp" ]] || [[ "$mp" == "/" ]]; then
            local df_line
            df_line="$(df -h "$mp" 2>/dev/null | tail -1 || true)"
            [[ -z "$df_line" ]] && continue
            local dev size used avail pct mount
            dev="$(echo "$df_line" | awk '{print $1}')"
            size="$(echo "$df_line" | awk '{print $2}')"
            used="$(echo "$df_line" | awk '{print $3}')"
            avail="$(echo "$df_line" | awk '{print $4}')"
            pct="$(echo "$df_line" | awk '{print $5}')"
            mount="$(echo "$df_line" | awk '{print $6}')"

            # Skip duplicates (e.g., / and /home on same partition)
            local already_seen="false"
            for seen in "${seen_devs[@]:-}"; do
                [[ "$seen" == "$dev" ]] && already_seen="true" && break
            done
            [[ "$already_seen" == "true" ]] && continue
            seen_devs+=("$dev")

            md "| ${mount} | ${dev} | ${size} | ${used} | ${avail} | ${pct} |"

            local pct_num="${pct%%%}"
            if [[ "$pct_num" =~ ^[0-9]+$ ]] && [[ "$pct_num" -ge 90 ]]; then
                log_warn "Disk ${mount}: ${pct} used"
                disk_warn="true"
            fi
        fi
    done
    md ""

    if [[ "$disk_warn" == "true" ]]; then
        SUMMARY_STATUS["Disk Space"]="WARN"
        SUMMARY_DETAIL["Disk Space"]="Partition(s) above 90% usage"
    else
        SUMMARY_STATUS["Disk Space"]="OK"
        SUMMARY_DETAIL["Disk Space"]="All partitions below 90%"
    fi
}

# ---------------------------------------------------------------------------
# Section: CPU
# ---------------------------------------------------------------------------

section_cpu() {
    log_section "CPU"

    if ! cmd_exists lscpu; then
        log_fail "lscpu not found"
        md "---"
        md ""
        md "## CPU"
        md ""
        md "> \`lscpu\` not found. Install \`util-linux\` for CPU details."
        md ""
        SUMMARY_STATUS["CPU"]="ERROR"
        SUMMARY_DETAIL["CPU"]="lscpu not found"
        return
    fi

    LSCPU_OUTPUT="$(lscpu 2>/dev/null)"

    local model cores threads sockets max_mhz min_mhz bogomips virt microcode

    model="$(lscpu_val "Model name")"
    cores="$(lscpu_val "Core(s) per socket")"
    threads="$(lscpu_val "CPU(s)")"
    sockets="$(lscpu_val "Socket(s)")"
    max_mhz="$(lscpu_val "CPU max MHz")"
    min_mhz="$(lscpu_val "CPU min MHz")"
    bogomips="$(lscpu_val "BogoMIPS")"
    virt="$(lscpu_val "Virtualization")"
    microcode="$(grep -m1 "^microcode" /proc/cpuinfo 2>/dev/null | awk '{print $NF}' || echo "N/A")"

    log_ok "${model} (${cores}C/${threads}T)"

    md "---"
    md ""
    md "## CPU"
    md ""
    md "| Field | Value |"
    md "|-------|-------|"
    md "| **Model** | ${model} |"
    md "| **Cores / Threads** | ${cores}C / ${threads}T |"
    md "| **Sockets** | ${sockets} |"
    md "| **Max Frequency** | ${max_mhz} MHz |"
    md "| **Min Frequency** | ${min_mhz} MHz |"
    md "| **BogoMIPS** | ${bogomips} |"
    md "| **Microcode** | ${microcode} |"
    md "| **Virtualization** | ${virt:-N/A} |"
    md ""

    # Cache hierarchy
    local l1d l1i l2 l3
    l1d="$(lscpu_val "L1d cache")"
    l1i="$(lscpu_val "L1i cache")"
    l2="$(lscpu_val "L2 cache")"
    l3="$(lscpu_val "L3 cache")"

    md "### Cache Hierarchy"
    md ""
    md "| Level | Size |"
    md "|-------|------|"
    md "| L1d | ${l1d:-N/A} |"
    md "| L1i | ${l1i:-N/A} |"
    md "| L2 | ${l2:-N/A} |"
    md "| L3 | ${l3:-N/A} |"
    md ""

    # Key ISA extensions
    local flags
    flags="$(lscpu_val "Flags")"
    local extensions=""
    for feat in avx avx2 avx512f avx512_bf16 sse4_1 sse4_2 aes sha_ni f16c fma; do
        if echo "$flags" | grep -qw "$feat"; then
            local label
            case $feat in
                avx)           label="AVX" ;;
                avx2)          label="AVX2" ;;
                avx512f)       label="AVX-512" ;;
                avx512_bf16)   label="AVX-512 BF16" ;;
                sse4_1)        label="SSE4.1" ;;
                sse4_2)        label="SSE4.2" ;;
                aes)           label="AES-NI" ;;
                sha_ni)        label="SHA-NI" ;;
                f16c)          label="F16C" ;;
                fma)           label="FMA" ;;
                *)             label="$feat" ;;
            esac
            extensions+=" \`${label}\`"
        fi
    done

    if [[ -n "$extensions" ]]; then
        md "### Key Instruction Set Extensions"
        md ""
        md "${extensions}"
        md ""
    fi

    SUMMARY_STATUS["CPU"]="OK"
    SUMMARY_DETAIL["CPU"]="${model}, ${cores}C/${threads}T"
}

# ---------------------------------------------------------------------------
# Section: Memory
# ---------------------------------------------------------------------------

section_memory() {
    log_section "Memory"

    local mem_total_kb mem_avail_kb swap_total_kb swap_free_kb
    mem_total_kb="$(awk '/^MemTotal:/ {print $2}' /proc/meminfo 2>/dev/null || echo "0")"
    mem_avail_kb="$(awk '/^MemAvailable:/ {print $2}' /proc/meminfo 2>/dev/null || echo "0")"
    swap_total_kb="$(awk '/^SwapTotal:/ {print $2}' /proc/meminfo 2>/dev/null || echo "0")"
    swap_free_kb="$(awk '/^SwapFree:/ {print $2}' /proc/meminfo 2>/dev/null || echo "0")"

    local mem_total_gib swap_total_gib swap_used_kb swap_used_gib mem_avail_gib
    mem_total_gib="$(echo "scale=1; $mem_total_kb / 1048576" | bc 2>/dev/null || echo "N/A")"
    mem_avail_gib="$(echo "scale=1; $mem_avail_kb / 1048576" | bc 2>/dev/null || echo "N/A")"
    swap_total_gib="$(echo "scale=1; $swap_total_kb / 1048576" | bc 2>/dev/null || echo "N/A")"
    swap_used_kb=$((swap_total_kb - swap_free_kb))
    swap_used_gib="$(echo "scale=1; $swap_used_kb / 1048576" | bc 2>/dev/null || echo "N/A")"

    log_ok "${mem_total_gib} GiB total, ${mem_avail_gib} GiB available"

    md "---"
    md ""
    md "## Memory"
    md ""
    md "| Field | Value |"
    md "|-------|-------|"
    md "| **Total RAM** | ${mem_total_gib} GiB (${mem_total_kb} KiB) |"
    md "| **Available RAM** | ${mem_avail_gib} GiB |"
    md "| **Swap Total** | ${swap_total_gib} GiB |"
    md "| **Swap Used** | ${swap_used_gib} GiB |"
    md ""

    # DIMM details via dmidecode (needs sudo)
    if cmd_exists dmidecode; then
        local dimm_output
        if dimm_output="$(try_sudo dmidecode -t memory 2>/dev/null)"; then
            local dimm_table
            dimm_table="$(echo "$dimm_output" | awk '
                /Memory Device$/ { in_dev=1; size=""; type=""; speed=""; locator=""; mfr="" }
                in_dev && /^\tSize:/ { size=$2 " " $3 }
                in_dev && /^\tType:/ { type=$2 }
                in_dev && /^\tSpeed:/ { speed=$2 " " $3 }
                in_dev && /^\tLocator:/ { locator=$2 }
                in_dev && /^\tManufacturer:/ { mfr=$2 }
                in_dev && /^$/ {
                    if (size != "" && size !~ /No Module/) {
                        printf "| %s | %s | %s | %s | %s |\n", locator, size, type, speed, mfr
                    }
                    in_dev=0
                }
            ')"

            if [[ -n "$dimm_table" ]]; then
                md "### DIMM Details (via dmidecode)"
                md ""
                md "| Locator | Size | Type | Speed | Manufacturer |"
                md "|---------|------|------|-------|--------------|"
                md "$dimm_table"
                md ""
            fi
        else
            md "> DIMM details require sudo. Run without \`--no-sudo\` for full info."
            md ""
        fi
    else
        md "> Install \`dmidecode\` for DIMM details."
        md ""
    fi

    SUMMARY_STATUS["Memory"]="OK"
    SUMMARY_DETAIL["Memory"]="${mem_total_gib} GiB"
}

# ---------------------------------------------------------------------------
# Section: GPU
# ---------------------------------------------------------------------------

section_gpu() {
    log_section "GPU"

    md "---"
    md ""
    md "## GPU"
    md ""

    if ! cmd_exists lspci; then
        log_fail "lspci not found"
        md "> \`lspci\` not found. Install \`pciutils\` for GPU details."
        md ""
        SUMMARY_STATUS["GPU"]="ERROR"
        SUMMARY_DETAIL["GPU"]="lspci not found"
        return
    fi

    # Find AMD display controllers (class 0300=VGA, 0380=Display controller)
    local gpu_lines
    gpu_lines="$(lspci -nn 2>/dev/null | grep -iE '\[(0300|0380)\]' | grep -i 'amd\|ati\|radeon' || true)"

    if [[ -z "$gpu_lines" ]]; then
        log_warn "No AMD GPU detected"
        md "> No AMD GPU detected via lspci."
        md ""
        SUMMARY_STATUS["GPU"]="NOT FOUND"
        SUMMARY_DETAIL["GPU"]="No AMD GPU detected"
        return
    fi

    # Process each GPU found
    local gpu_count=0
    while IFS= read -r gpu_line; do
        gpu_count=$((gpu_count + 1))
        local bdf dev_name vendor_device_id

        bdf="$(echo "$gpu_line" | awk '{print $1}')"
        # Extract vendor:device from the [xxxx:xxxx] pattern
        vendor_device_id="$(echo "$gpu_line" | grep -oP '\[\w{4}:\w{4}\]' | head -1 | tr -d '[]')"
        # Extract device name (between the class code and the final [vendor:device])
        dev_name="$(echo "$gpu_line" | sed 's/^[^ ]* [^:]*: //' | sed 's/ \[[0-9a-f]\{4\}:[0-9a-f]\{4\}\].*$//')"

        local gpu_rev=""
        local driver=""
        local vram_info=""

        # Get detailed info
        local detail
        detail="$(lspci -v -s "$bdf" 2>/dev/null || true)"
        if [[ -n "$detail" ]]; then
            driver="$(echo "$detail" | grep -m1 "Kernel driver in use:" | sed 's/.*: //')"
            gpu_rev="$(echo "$detail" | grep -m1 "(rev " | grep -oP 'rev \w+' | head -1 | awk '{print $2}')"
            vram_info="$(echo "$detail" | grep -m1 "prefetchable" | grep -oP 'size=\w+' | head -1 || true)"
        fi

        local gpu_type="Integrated"
        # Class 0300 = VGA (often discrete), 0380 = Display controller (often integrated)
        if echo "$gpu_line" | grep -q '\[0300\]'; then
            gpu_type="Discrete/VGA"
        fi

        log_ok "${dev_name} (${bdf}, ${driver:-no driver})"

        md "### GPU ${gpu_count}: ${dev_name}"
        md ""
        md "| Field | Value |"
        md "|-------|-------|"
        md "| **Device** | ${dev_name} |"
        md "| **Type** | ${gpu_type} |"
        md "| **PCI Address** | ${bdf} |"
        md "| **Vendor:Device ID** | ${vendor_device_id} |"
        [[ -n "$gpu_rev" ]] && md "| **Revision** | ${gpu_rev} |"
        md "| **Driver** | ${driver:-N/A} |"
        [[ -n "$vram_info" ]] && md "| **VRAM BAR** | ${vram_info} |"
        md ""

        SUMMARY_STATUS["GPU"]="OK"
        SUMMARY_DETAIL["GPU"]="${dev_name} (${driver:-N/A})"

    done <<< "$gpu_lines"

    # OpenGL info
    if [[ -n "${DISPLAY:-}${WAYLAND_DISPLAY:-}" ]] && cmd_exists glxinfo; then
        local renderer gl_version gl_vendor
        renderer="$(glxinfo 2>/dev/null | grep -m1 "OpenGL renderer" | sed 's/.*: //' || true)"
        gl_version="$(glxinfo 2>/dev/null | grep -m1 "OpenGL version" | sed 's/.*: //' || true)"
        gl_vendor="$(glxinfo 2>/dev/null | grep -m1 "OpenGL vendor" | sed 's/.*: //' || true)"

        if [[ -n "$renderer" ]]; then
            md "### OpenGL"
            md ""
            md "| Field | Value |"
            md "|-------|-------|"
            md "| **Vendor** | ${gl_vendor} |"
            md "| **Renderer** | ${renderer} |"
            md "| **Version** | ${gl_version} |"
            md ""
        fi
    else
        md "> OpenGL info: N/A (no display server or \`glxinfo\` not found)"
        md ""
    fi

    # Vulkan info
    if cmd_exists vulkaninfo; then
        local vk_device
        vk_device="$(vulkaninfo --summary 2>/dev/null | grep -m1 "deviceName" | sed 's/.*= //' || true)"
        if [[ -n "$vk_device" ]]; then
            md "### Vulkan"
            md ""
            md "| Field | Value |"
            md "|-------|-------|"
            md "| **Device** | ${vk_device} |"
            md ""
        fi
    fi

    # VAAPI status (hardware video encoding/decoding)
    md "### VAAPI Status"
    md ""
    if cmd_exists vainfo; then
        local vaapi_driver
        vaapi_driver="$(vainfo 2>/dev/null | grep -m1 "Driver version" | sed 's/.*: //' || echo "unknown")"
        local vaapi_profiles
        vaapi_profiles="$(vainfo 2>/dev/null | grep -c "VAProfile" || echo "0")"
        md "| Field | Value |"
        md "|-------|-------|"
        md "| **Driver** | ${vaapi_driver} |"
        md "| **Profiles** | ${vaapi_profiles} |"
        md ""
        log_ok "VAAPI: ${vaapi_driver}"
        SUMMARY_STATUS["VAAPI"]="OK"
        SUMMARY_DETAIL["VAAPI"]="${vaapi_driver}"
    else
        md "> \`vainfo\` not found. Install \`libva-utils\` for VAAPI status."
        md ""
        SUMMARY_STATUS["VAAPI"]="NOT FOUND"
        SUMMARY_DETAIL["VAAPI"]="vainfo not found"
    fi

    # GPU device nodes (important for K8s container passthrough)
    md "### GPU/Accelerator Device Nodes"
    md ""
    md "| Device | Exists | Permissions | Purpose |"
    md "|--------|--------|-------------|---------|"

    for dev_check in "/dev/dri:GPU rendering (ROCm + VAAPI)" "/dev/kfd:ROCm compute kernel" "/dev/accel/accel0:NPU (amdxdna)"; do
        local dev_path="${dev_check%%:*}"
        local dev_purpose="${dev_check##*:}"
        if [[ -e "$dev_path" ]]; then
            local dev_perms
            dev_perms="$(stat -c '%A (%a) %U:%G' "$dev_path" 2>/dev/null || echo "unknown")"
            md "| \`${dev_path}\` | Yes | ${dev_perms} | ${dev_purpose} |"
        else
            md "| \`${dev_path}\` | **No** | -- | ${dev_purpose} |"
        fi
    done
    md ""

    # GPU memory from sysfs (unified memory on Strix Halo)
    md "### GPU Memory (sysfs)"
    md ""
    local gpu_mem_found="false"
    for card_dir in /sys/class/drm/card*/device; do
        if [[ -f "$card_dir/mem_info_vram_total" ]]; then
            local vram_total vram_used vram_total_gib vram_used_gib card_name
            card_name="$(basename "$(dirname "$card_dir")")"
            vram_total="$(cat "$card_dir/mem_info_vram_total" 2>/dev/null || echo "0")"
            vram_used="$(cat "$card_dir/mem_info_vram_used" 2>/dev/null || echo "0")"
            vram_total_gib="$(echo "scale=1; $vram_total / 1073741824" | bc 2>/dev/null || echo "N/A")"
            vram_used_gib="$(echo "scale=2; $vram_used / 1073741824" | bc 2>/dev/null || echo "N/A")"
            md "| Field | Value |"
            md "|-------|-------|"
            md "| **Card** | ${card_name} |"
            md "| **VRAM Total** | ${vram_total_gib} GiB |"
            md "| **VRAM Used** | ${vram_used_gib} GiB |"

            # GTT (system memory allocated to GPU) — important for unified memory APUs
            if [[ -f "$card_dir/mem_info_gtt_total" ]]; then
                local gtt_total gtt_used gtt_total_gib gtt_used_gib
                gtt_total="$(cat "$card_dir/mem_info_gtt_total" 2>/dev/null || echo "0")"
                gtt_used="$(cat "$card_dir/mem_info_gtt_used" 2>/dev/null || echo "0")"
                gtt_total_gib="$(echo "scale=1; $gtt_total / 1073741824" | bc 2>/dev/null || echo "N/A")"
                gtt_used_gib="$(echo "scale=2; $gtt_used / 1073741824" | bc 2>/dev/null || echo "N/A")"
                md "| **GTT Total** | ${gtt_total_gib} GiB |"
                md "| **GTT Used** | ${gtt_used_gib} GiB |"
            fi

            # Power state
            if [[ -f "$card_dir/power_dpm_force_performance_level" ]]; then
                local perf_level
                perf_level="$(cat "$card_dir/power_dpm_force_performance_level" 2>/dev/null || echo "N/A")"
                md "| **Performance Level** | ${perf_level} |"
            fi

            md ""
            gpu_mem_found="true"
        fi
    done
    if [[ "$gpu_mem_found" == "false" ]]; then
        md "> No GPU memory info found in sysfs. May require \`amdgpu\` driver."
        md ""
    fi

    # GPU Firmware versions (from sysfs)
    local fw_found="false"
    for card_dir in /sys/class/drm/card*/device; do
        if [[ -d "$card_dir/fw_version" ]]; then
            local card_name_fw
            card_name_fw="$(basename "$(dirname "$card_dir")")"

            md "### GPU Firmware (${card_name_fw})"
            md ""
            md "| Firmware | Version |"
            md "|----------|---------|"
            for fw_file in "$card_dir"/fw_version/*; do
                [[ -f "$fw_file" ]] || continue
                local fw_name fw_val
                fw_name="$(basename "$fw_file")"
                fw_val="$(cat "$fw_file" 2>/dev/null || echo "N/A")"
                md "| ${fw_name} | \`${fw_val}\` |"
            done

            # VBIOS version
            if [[ -f "$card_dir/vbios_version" ]]; then
                local vbios
                vbios="$(cat "$card_dir/vbios_version" 2>/dev/null || echo "N/A")"
                md "| VBIOS | \`${vbios}\` |"
            fi
            md ""

            # Clock frequencies
            if [[ -f "$card_dir/pp_dpm_sclk" ]] || [[ -f "$card_dir/pp_dpm_mclk" ]]; then
                md "### GPU Clocks (${card_name_fw})"
                md ""
                md "| Field | Value |"
                md "|-------|-------|"

                if [[ -f "$card_dir/pp_dpm_sclk" ]]; then
                    local sclk_current sclk_max
                    sclk_current="$(cat "$card_dir/pp_dpm_sclk" 2>/dev/null | grep '\*' | awk '{print $2}' || echo "N/A")"
                    sclk_max="$(cat "$card_dir/pp_dpm_sclk" 2>/dev/null | tail -1 | awk '{print $2}' || echo "N/A")"
                    md "| **GPU Clock (current)** | ${sclk_current} |"
                    md "| **GPU Clock (max)** | ${sclk_max} |"
                fi
                if [[ -f "$card_dir/pp_dpm_mclk" ]]; then
                    local mclk_current mclk_max
                    mclk_current="$(cat "$card_dir/pp_dpm_mclk" 2>/dev/null | grep '\*' | awk '{print $2}' || echo "N/A")"
                    mclk_max="$(cat "$card_dir/pp_dpm_mclk" 2>/dev/null | tail -1 | awk '{print $2}' || echo "N/A")"
                    md "| **Memory Clock (current)** | ${mclk_current} |"
                    md "| **Memory Clock (max)** | ${mclk_max} |"
                fi
                md ""
            fi

            fw_found="true"
        fi
    done
    if [[ "$fw_found" == "false" ]]; then
        md "### GPU Firmware"
        md ""
        md "> No GPU firmware version info found in sysfs."
        md ""
    fi

    # ROCm status
    md "### ROCm Status"
    md ""
    if cmd_exists rocminfo; then
        local rocm_ver
        rocm_ver="$(rocminfo 2>/dev/null | grep -m1 "Runtime Version" | awk '{print $NF}' || echo "unknown")"
        md "ROCm runtime version: ${rocm_ver}"

        # Extract GPU agent details (gfx target)
        local gfx_target
        gfx_target="$(rocminfo 2>/dev/null | grep -m1 "Name:" | grep -oP 'gfx\w+' || true)"
        if [[ -n "$gfx_target" ]]; then
            md ""
            md "GPU agent: \`${gfx_target}\`"
        fi
        md ""
        log_ok "ROCm installed (${rocm_ver})"
    elif cmd_exists rocm-smi; then
        md "ROCm SMI available but \`rocminfo\` not found."
        md ""
        log_warn "ROCm partially installed"
    else
        md "ROCm is **not installed**. (\`rocminfo\` and \`rocm-smi\` not found)"
        md ""
        log_warn "ROCm not installed"
    fi

    # amdgpu kernel messages
    local amdgpu_kmsgs=""
    amdgpu_kmsgs="$(journalctl -k --no-pager 2>/dev/null | grep -i amdgpu | tail -50 || true)"
    if [[ -z "$amdgpu_kmsgs" ]] && [[ "$SUDO_AVAILABLE" == "true" ]]; then
        amdgpu_kmsgs="$(try_sudo dmesg 2>/dev/null | grep -i amdgpu | tail -50 || true)"
    fi

    if [[ -n "$amdgpu_kmsgs" ]]; then
        md "### Kernel Messages (amdgpu)"
        md ""
        md "<details>"
        md "<summary>Click to expand</summary>"
        md ""
        md "\`\`\`"
        md "$amdgpu_kmsgs"
        md "\`\`\`"
        md ""
        md "</details>"
        md ""

        if echo "$amdgpu_kmsgs" | grep -qi "error\|fault\|timeout\|firmware.*fail"; then
            log_warn "amdgpu: errors detected in kernel log"
        else
            log_ok "amdgpu: kernel messages collected (no errors)"
        fi
    fi
}

# ---------------------------------------------------------------------------
# Section: NPU
# ---------------------------------------------------------------------------

section_npu() {
    log_section "NPU (Neural Processing Unit)"

    md "---"
    md ""
    md "## NPU (Neural Processing Unit)"
    md ""

    if ! cmd_exists lspci; then
        log_fail "lspci not found"
        md "> \`lspci\` not found. Install \`pciutils\` for NPU detection."
        md ""
        SUMMARY_STATUS["NPU"]="ERROR"
        SUMMARY_DETAIL["NPU"]="lspci not found"
        return
    fi

    # Search for known AMD NPU device IDs
    local npu_line
    npu_line="$(lspci -nn 2>/dev/null | grep -iE '1022:(17f0|1502)' | head -1 || true)"

    if [[ -z "$npu_line" ]]; then
        log_fail "No AMD NPU detected"
        md "> No AMD NPU detected. Searched for device IDs: \`1022:17f0\`, \`1022:1502\`."
        md ""
        SUMMARY_STATUS["NPU"]="NOT FOUND"
        SUMMARY_DETAIL["NPU"]="No AMD NPU detected"
        SUMMARY_STATUS["NPU Device Node"]="N/A"
        SUMMARY_DETAIL["NPU Device Node"]="No NPU"
        SUMMARY_STATUS["NPU Firmware"]="N/A"
        SUMMARY_DETAIL["NPU Firmware"]="No NPU"
        SUMMARY_STATUS["XRT"]="N/A"
        SUMMARY_DETAIL["XRT"]="No NPU"
        return
    fi

    local bdf dev_name vendor_device_id
    bdf="$(echo "$npu_line" | awk '{print $1}')"
    vendor_device_id="$(echo "$npu_line" | grep -oP '1022:\w{4}' | head -1 | tr '[:upper:]' '[:lower:]')"
    dev_name="$(echo "$npu_line" | sed 's/^[^ ]* [^:]*: //' | sed 's/ \[[0-9a-f]\{4\}:[0-9a-f]\{4\}\].*$//')"

    # Get revision
    local npu_rev="" driver=""
    local detail
    detail="$(lspci -v -s "$bdf" 2>/dev/null || true)"
    if [[ -n "$detail" ]]; then
        driver="$(echo "$detail" | grep -m1 "Kernel driver in use:" | sed 's/.*: //')"
        npu_rev="$(echo "$detail" | grep -m1 "(rev " | grep -oP 'rev \w+' | head -1 | awk '{print $2}')"
    fi

    # Map to generation name
    local dev_id_short="${vendor_device_id#1022:}"
    local lookup_key="${dev_id_short}:${npu_rev:-00}"
    local generation="${NPU_DEVICE_MAP[$lookup_key]:-Unknown (${dev_id_short} rev ${npu_rev:-??})}"

    log_ok "${generation} (${vendor_device_id} rev ${npu_rev:-??})"

    md "| Field | Value |"
    md "|-------|-------|"
    md "| **Device** | ${dev_name} |"
    md "| **PCI Address** | ${bdf} |"
    md "| **Vendor:Device ID** | ${vendor_device_id} |"
    md "| **Revision** | ${npu_rev:-N/A} |"
    md "| **Generation** | ${generation} |"
    md "| **Driver** | ${driver:-N/A} |"

    # Driver module info
    if cmd_exists modinfo; then
        local driver_path driver_version
        driver_path="$(modinfo -F filename amdxdna 2>/dev/null || echo "")"
        driver_version="$(modinfo -F version amdxdna 2>/dev/null || echo "")"
        [[ -n "$driver_path" ]] && md "| **Driver Module** | \`${driver_path}\` |"
        [[ -n "$driver_version" ]] && md "| **Driver Version** | ${driver_version} |"
    fi

    # Device node
    local dev_node_status="NOT FOUND"
    local dev_node_detail="No /dev/accel/ entries"
    if [[ -d /dev/accel ]]; then
        local accel_dev
        accel_dev="$(ls /dev/accel/ 2>/dev/null | head -1 || true)"
        if [[ -n "$accel_dev" ]]; then
            local perms
            perms="$(stat -c '%A (%a)' "/dev/accel/${accel_dev}" 2>/dev/null || echo "unknown")"
            md "| **Device Node** | /dev/accel/${accel_dev} |"
            md "| **Device Permissions** | ${perms} |"
            dev_node_status="OK"
            dev_node_detail="/dev/accel/${accel_dev} ${perms}"

            # Check if permissions are accessible
            local perm_octal
            perm_octal="$(stat -c '%a' "/dev/accel/${accel_dev}" 2>/dev/null || echo "000")"
            if [[ "$perm_octal" -lt 660 ]]; then
                log_warn "Device permissions may be too restrictive: ${perms}"
                dev_node_status="WARN"
            else
                log_ok "Device node: /dev/accel/${accel_dev} (${perms})"
            fi
        fi
    else
        md "| **Device Node** | /dev/accel/ not found |"
        log_fail "No /dev/accel/ directory"
    fi

    # Sysfs path
    if [[ -d /sys/class/accel ]]; then
        local sysfs_link
        sysfs_link="$(readlink -f /sys/class/accel/accel0 2>/dev/null || echo "")"
        [[ -n "$sysfs_link" ]] && md "| **Sysfs Path** | ${sysfs_link} |"
    fi

    md ""

    # IOMMU & SVA Configuration
    md "### IOMMU & SVA Configuration"
    md ""
    md "| Field | Value |"
    md "|-------|-------|"

    local iommu_group_count=0
    if [[ -d /sys/kernel/iommu_groups ]]; then
        iommu_group_count="$(ls /sys/kernel/iommu_groups/ 2>/dev/null | wc -l)"
        md "| **IOMMU Groups** | ${iommu_group_count} |"
    else
        md "| **IOMMU Groups** | Not available |"
    fi

    if [[ -d /sys/class/iommu ]]; then
        local iommu_instances
        iommu_instances="$(ls /sys/class/iommu/ 2>/dev/null | tr '\n' ', ' | sed 's/,$//' || true)"
        md "| **IOMMU Instances** | ${iommu_instances:-none} |"
    fi

    # NPU's IOMMU group
    local npu_iommu_group=""
    if [[ -L /sys/class/accel/accel0/device/iommu_group ]]; then
        npu_iommu_group="$(readlink /sys/class/accel/accel0/device/iommu_group 2>/dev/null | grep -oP '\d+$' || true)"
        md "| **NPU IOMMU Group** | ${npu_iommu_group:-unknown} |"
        if [[ -n "$npu_iommu_group" && -d "/sys/kernel/iommu_groups/${npu_iommu_group}/devices" ]]; then
            local group_devices
            group_devices="$(ls "/sys/kernel/iommu_groups/${npu_iommu_group}/devices/" 2>/dev/null | tr '\n' ', ' | sed 's/,$//')"
            md "| **Group ${npu_iommu_group} Devices** | ${group_devices} |"
        fi
    fi

    # Kernel cmdline IOMMU parameters
    local iommu_cmdline
    iommu_cmdline="$(cat /proc/cmdline 2>/dev/null || true)"
    local iommu_params=""
    for param in iommu amd_iommu iommu.passthrough iommu.strict; do
        local ival
        ival="$(echo "$iommu_cmdline" | tr ' ' '\n' | grep "^${param}=" | head -1 || true)"
        [[ -n "$ival" ]] && iommu_params+="${ival}, "
    done
    iommu_params="${iommu_params%, }"
    md "| **IOMMU Kernel Params** | ${iommu_params:-none (defaults)} |"

    # SVA readiness heuristic
    local sva_status="unknown"
    if [[ $iommu_group_count -gt 0 && -n "$npu_iommu_group" ]]; then
        sva_status="IOMMU active (${iommu_group_count} groups) — NPU in group ${npu_iommu_group}"
    elif [[ $iommu_group_count -gt 0 ]]; then
        sva_status="IOMMU active (${iommu_group_count} groups) — NPU group not identified"
    else
        sva_status="IOMMU not active — SVA will fail"
    fi
    md "| **SVA Status** | ${sva_status} |"
    md ""

    if [[ $iommu_group_count -gt 0 && -n "$npu_iommu_group" ]]; then
        log_ok "IOMMU: ${iommu_group_count} groups, NPU in group ${npu_iommu_group}"
    elif [[ $iommu_group_count -gt 0 ]]; then
        log_ok "IOMMU: ${iommu_group_count} groups (NPU group not identified)"
    else
        log_warn "IOMMU: no groups found — NPU SVA will fail"
    fi

    SUMMARY_STATUS["NPU"]="OK"
    SUMMARY_DETAIL["NPU"]="${generation} ${dev_id_short} rev ${npu_rev:-??}"
    SUMMARY_STATUS["NPU Device Node"]="$dev_node_status"
    SUMMARY_DETAIL["NPU Device Node"]="$dev_node_detail"

    # Firmware
    md "### Firmware"
    md ""
    if [[ -d /lib/firmware/amdnpu ]]; then
        md "| Directory | Contents |"
        md "|-----------|----------|"
        local fw_found="false"
        for fw_dir in /lib/firmware/amdnpu/*/; do
            if [[ -d "$fw_dir" ]]; then
                local dir_name files
                dir_name="$(basename "$fw_dir")"
                files="$(ls "$fw_dir" 2>/dev/null | tr '\n' ', ' | sed 's/,$//')"
                md "| \`${dir_name}/\` | ${files:-empty} |"
                fw_found="true"
            fi
        done
        md ""

        # Match firmware to detected device
        local expected_fw_dir="${dev_id_short}_${npu_rev:-00}"
        if [[ -d "/lib/firmware/amdnpu/${expected_fw_dir}" ]]; then
            log_ok "Firmware: ${expected_fw_dir}/"
            SUMMARY_STATUS["NPU Firmware"]="OK"
            SUMMARY_DETAIL["NPU Firmware"]="${expected_fw_dir}/"
        else
            log_warn "Expected firmware dir ${expected_fw_dir}/ not found"
            SUMMARY_STATUS["NPU Firmware"]="WARN"
            SUMMARY_DETAIL["NPU Firmware"]="Expected ${expected_fw_dir}/ not found"
        fi
    else
        md "> Firmware directory \`/lib/firmware/amdnpu/\` not found."
        md ""
        log_fail "No firmware directory"
        SUMMARY_STATUS["NPU Firmware"]="NOT FOUND"
        SUMMARY_DETAIL["NPU Firmware"]="/lib/firmware/amdnpu/ not found"
    fi

    # XRT
    md "### XRT (Xilinx Runtime)"
    md ""
    if [[ -f /usr/xrt/version.json ]]; then
        local xrt_version xrt_date
        xrt_version="$(python3 -c "import json; d=json.load(open('/usr/xrt/version.json')); print(d.get('BUILD_VERSION','unknown'))" 2>/dev/null \
            || grep -oP '"BUILD_VERSION"\s*:\s*"\K[^"]+' /usr/xrt/version.json 2>/dev/null \
            || echo "unknown")"
        xrt_date="$(python3 -c "import json; d=json.load(open('/usr/xrt/version.json')); print(d.get('BUILD_DATE','unknown'))" 2>/dev/null \
            || grep -oP '"BUILD_DATE"\s*:\s*"\K[^"]+' /usr/xrt/version.json 2>/dev/null \
            || echo "unknown")"

        md "| Field | Value |"
        md "|-------|-------|"
        md "| **XRT Version** | ${xrt_version} |"
        md "| **Build Date** | ${xrt_date} |"
        md "| **XRT Path** | /usr/xrt/ |"

        # Check xrt-smi
        if [[ -x /usr/xrt/bin/xrt-smi ]]; then
            md "| **xrt-smi** | \`/usr/xrt/bin/xrt-smi\` (available) |"
        else
            md "| **xrt-smi** | Not found |"
        fi

        # Check xbutil / xbmgmt2
        for tool in xbutil xbmgmt2 xclbinutil; do
            if [[ -x "/usr/xrt/bin/${tool}" ]]; then
                md "| **${tool}** | \`/usr/xrt/bin/${tool}\` (available) |"
            fi
        done
        md ""

        # xrt-smi examine output
        if [[ -x /usr/xrt/bin/xrt-smi ]]; then
            local xrt_examine
            xrt_examine="$(/usr/xrt/bin/xrt-smi examine 2>&1 || true)"
            if [[ -n "$xrt_examine" ]]; then
                md "### xrt-smi Examine"
                md ""
                md "<details>"
                md "<summary>Click to expand</summary>"
                md ""
                md "\`\`\`"
                md "$xrt_examine"
                md "\`\`\`"
                md ""
                md "</details>"
                md ""

                if echo "$xrt_examine" | grep -qi "ERROR.*No devices found"; then
                    log_warn "xrt-smi examine: No devices found (kernel regression?)"
                elif echo "$xrt_examine" | grep -qi "error"; then
                    log_warn "xrt-smi examine: errors detected"
                else
                    log_ok "xrt-smi examine: device detected"
                fi
            fi
        fi

        log_ok "XRT v${xrt_version}"
        SUMMARY_STATUS["XRT"]="OK"
        SUMMARY_DETAIL["XRT"]="v${xrt_version}"
    elif [[ -d /opt/xilinx/xrt ]] || [[ -d /usr/xrt ]]; then
        md "XRT directory found but \`version.json\` missing."
        md ""
        log_warn "XRT found but version unknown"
        SUMMARY_STATUS["XRT"]="WARN"
        SUMMARY_DETAIL["XRT"]="Directory found, version unknown"
    else
        md "XRT is **not installed**."
        md ""
        log_warn "XRT not installed"
        SUMMARY_STATUS["XRT"]="NOT INSTALLED"
        SUMMARY_DETAIL["XRT"]="--"
    fi

    # Kernel messages for amdxdna
    local kmsgs=""
    kmsgs="$(journalctl -k --no-pager 2>/dev/null | grep -i amdxdna || true)"
    if [[ -z "$kmsgs" ]] && [[ "$SUDO_AVAILABLE" == "true" ]]; then
        kmsgs="$(try_sudo dmesg 2>/dev/null | grep -i amdxdna || true)"
    fi

    if [[ -n "$kmsgs" ]]; then
        md "### Kernel Messages (amdxdna)"
        md ""
        md "<details>"
        md "<summary>Click to expand</summary>"
        md ""
        md "\`\`\`"
        md "$kmsgs"
        md "\`\`\`"
        md ""
        md "</details>"
        md ""
    fi

    # VAIP Pass Plugins — detect which VitisAI compiler passes are available
    md "### VAIP Pass Plugins"
    md ""

    local vaip_search_dirs=()
    local cvml_ryzen14="${SCRIPT_DIR}/Ryzen-AI-CVML-Library/linux/onnx/ryzen14"
    [[ -d "$cvml_ryzen14" ]] && vaip_search_dirs+=("$cvml_ryzen14")
    [[ -n "${ONNXRUNTIME_ROOTDIR:-}" && -d "${ONNXRUNTIME_ROOTDIR}/lib" ]] && vaip_search_dirs+=("${ONNXRUNTIME_ROOTDIR}/lib")
    if [[ -n "${LD_LIBRARY_PATH:-}" ]]; then
        local IFS=:
        for ld_dir in $LD_LIBRARY_PATH; do
            [[ -d "$ld_dir" ]] && vaip_search_dirs+=("$ld_dir")
        done
        unset IFS
    fi

    local vaip_found="false"
    local vaiml_partition_found="false"
    local vaip_pass_count=0

    for dir in "${vaip_search_dirs[@]}"; do
        local passes
        passes="$(ls "$dir"/libvaip-pass_*.so 2>/dev/null || true)"
        if [[ -n "$passes" ]]; then
            vaip_found="true"
            md "**Found in \`${dir}/\`:**"
            md ""
            md "| Plugin | Size |"
            md "|--------|------|"
            while IFS= read -r pass_lib; do
                local pass_name pass_size
                pass_name="$(basename "$pass_lib")"
                pass_size="$(du -h "$pass_lib" 2>/dev/null | awk '{print $1}')"
                md "| \`${pass_name}\` | ${pass_size} |"
                vaip_pass_count=$((vaip_pass_count + 1))
                if [[ "$pass_name" == "libvaip-pass_vaiml_partition.so" ]]; then
                    vaiml_partition_found="true"
                fi
            done <<< "$passes"
            md ""
        fi
    done

    # Also check for key VAIP infrastructure libraries
    local vaip_core_found="false"
    local xcompiler_found="false"
    local vitisai_ep_found="false"
    for dir in "${vaip_search_dirs[@]}"; do
        [[ -f "${dir}/libvaip-core.so" ]] && vaip_core_found="true"
        [[ -f "${dir}/libxcompiler-core-without-symbol.so" ]] && xcompiler_found="true"
        [[ -f "${dir}/libonnxruntime_vitisai_ep.so" ]] && vitisai_ep_found="true"
    done

    if [[ "$vaip_found" == "true" ]]; then
        md "| Infrastructure Library | Found |"
        md "|----------------------|-------|"
        md "| \`libvaip-core.so\` | ${vaip_core_found} |"
        md "| \`libxcompiler-core-without-symbol.so\` | ${xcompiler_found} |"
        md "| \`libonnxruntime_vitisai_ep.so\` | ${vitisai_ep_found} |"
        md ""
    fi

    if [[ "$vaiml_partition_found" == "true" ]]; then
        md "> **vaiml_partition pass:** Found — NPU offload for Whisper/BF16 models is available."
        log_ok "vaip-pass_vaiml_partition: found"
        SUMMARY_STATUS["VAIP Passes"]="OK"
        SUMMARY_DETAIL["VAIP Passes"]="vaiml_partition available (${vaip_pass_count} passes total)"
    elif [[ "$vaip_found" == "true" ]]; then
        md "> **vaiml_partition pass: NOT FOUND** — Required for NPU offload of Whisper and BF16 transformer models. Not shipped in CVML Linux deployment libs. ${vaip_pass_count} other pass(es) found."
        log_warn "vaip-pass_vaiml_partition: NOT FOUND (NPU offload blocked)"
        SUMMARY_STATUS["VAIP Passes"]="BLOCKED"
        SUMMARY_DETAIL["VAIP Passes"]="vaiml_partition MISSING (${vaip_pass_count} other passes)"
    else
        md "> No VAIP pass plugins found. Searched: ${vaip_search_dirs[*]:-none}"
        log_warn "No VAIP passes found"
        SUMMARY_STATUS["VAIP Passes"]="NOT FOUND"
        SUMMARY_DETAIL["VAIP Passes"]="No passes in search paths"
    fi
    md ""

    # XCLBIN Overlay Details
    local cvml_xclbin_dir="${SCRIPT_DIR}/Ryzen-AI-CVML-Library/linux/onnx/ryzen14"
    local xclbin_files
    xclbin_files="$(ls "${cvml_xclbin_dir}"/*.xclbin 2>/dev/null || true)"

    if [[ -n "$xclbin_files" ]]; then
        md "### XCLBIN Overlays"
        md ""
        md "| File | Overlay Type | Size | UUID |"
        md "|------|-------------|------|------|"

        while IFS= read -r xclbin_path; do
            [[ -z "$xclbin_path" ]] && continue
            local xclbin_name xclbin_size overlay_type xclbin_uuid
            xclbin_name="$(basename "$xclbin_path")"
            xclbin_size="$(du -h "$xclbin_path" 2>/dev/null | awk '{print $1}')"

            # Parse overlay type from filename
            overlay_type="unknown"
            if [[ "$xclbin_name" == *"4x4"*"CFG"* ]]; then
                overlay_type="4x4 (CFG variant)"
            elif [[ "$xclbin_name" == *"4x4"* ]]; then
                overlay_type="4x4"
            elif [[ "$xclbin_name" == *"8x4x1"* ]]; then
                overlay_type="8x4x1"
            elif [[ "$xclbin_name" == *"Nx4"* ]]; then
                overlay_type="Nx4"
            fi

            # Extract UUID via xclbinutil if available
            xclbin_uuid="N/A"
            if [[ -x /usr/xrt/bin/xclbinutil ]]; then
                xclbin_uuid="$(/usr/xrt/bin/xclbinutil --info --input "$xclbin_path" 2>/dev/null \
                    | grep -m1 "UUID (xclbin):" | sed 's/.*: *//' || echo "N/A")"
            fi

            md "| \`${xclbin_name}\` | ${overlay_type} | ${xclbin_size} | \`${xclbin_uuid}\` |"
        done <<< "$xclbin_files"
        md ""

        local xclbin_count
        xclbin_count="$(echo "$xclbin_files" | wc -l)"
        log_ok "XCLBIN overlays: ${xclbin_count} files"
    fi
}

# ---------------------------------------------------------------------------
# Section: Software Environment
# ---------------------------------------------------------------------------

section_software() {
    log_section "Software Environment"

    md "---"
    md ""
    md "## Software Environment"
    md ""

    # Python & package management
    md "### Python & Package Management"
    md ""
    md "| Field | Value |"
    md "|-------|-------|"

    if cmd_exists python3; then
        local py_ver py_path
        py_ver="$(python3 --version 2>/dev/null | awk '{print $2}')"
        py_path="$(which python3 2>/dev/null)"
        md "| **Python** | ${py_ver} (\`${py_path}\`) |"
        log_ok "Python ${py_ver}"
    else
        md "| **Python** | Not found |"
        log_fail "Python3 not found"
    fi

    if cmd_exists conda; then
        local conda_ver active_env
        conda_ver="$(conda --version 2>/dev/null | awk '{print $2}')"
        active_env="${CONDA_DEFAULT_ENV:-none}"
        md "| **Conda** | ${conda_ver} |"
        md "| **Active Env** | ${active_env} |"
        log_ok "Conda ${conda_ver} (env: ${active_env})"
    else
        md "| **Conda** | Not found |"
    fi

    if cmd_exists pip; then
        local pip_ver
        pip_ver="$(pip --version 2>/dev/null | awk '{print $2}')"
        md "| **pip** | ${pip_ver} |"
    fi

    md ""

    # Ryzen AI SDK
    md "### Ryzen AI SDK"
    md ""
    md "| Field | Value |"
    md "|-------|-------|"

    local rai_path="${RYZEN_AI_INSTALLATION_PATH:-}"
    if [[ -n "$rai_path" ]]; then
        md "| **RYZEN_AI_INSTALLATION_PATH** | \`${rai_path}\` |"
        SUMMARY_STATUS["Ryzen AI SDK"]="OK"
        SUMMARY_DETAIL["Ryzen AI SDK"]="${rai_path}"
    else
        md "| **RYZEN_AI_INSTALLATION_PATH** | *not set* |"
        SUMMARY_STATUS["Ryzen AI SDK"]="NOT CONFIGURED"
        SUMMARY_DETAIL["Ryzen AI SDK"]="Env var not set"
    fi

    local xlnx_fw="${XLNX_VART_FIRMWARE:-}"
    if [[ -n "$xlnx_fw" ]]; then
        md "| **XLNX_VART_FIRMWARE** | \`${xlnx_fw}\` |"
    else
        md "| **XLNX_VART_FIRMWARE** | *not set* |"
    fi

    md ""

    # Key packages
    md "### Key Packages"
    md ""
    md "| Package | Version | Status |"
    md "|---------|---------|--------|"

    local packages=(
        "onnxruntime"
        "onnxruntime-vitisai:onnxruntime_vitisai"
        "onnxruntime-genai:onnxruntime_genai"
        "voe"
        "quark"
        "torch"
        "numpy"
        "onnx"
    )

    local ort_installed="false"

    for pkg_entry in "${packages[@]}"; do
        local display_name import_name
        if [[ "$pkg_entry" == *":"* ]]; then
            display_name="${pkg_entry%%:*}"
            import_name="${pkg_entry##*:}"
        else
            display_name="$pkg_entry"
            import_name="$pkg_entry"
        fi

        local ver
        if cmd_exists python3; then
            ver="$(python3 -c "import ${import_name}; print(${import_name}.__version__)" 2>/dev/null || echo "")"
        fi

        if [[ -n "$ver" ]]; then
            md "| ${display_name} | ${ver} | Installed |"
            if [[ "$display_name" == "onnxruntime"* ]]; then
                ort_installed="true"
            fi
        else
            md "| ${display_name} | -- | Not installed |"
        fi
    done

    md ""

    if [[ "$ort_installed" == "true" ]]; then
        SUMMARY_STATUS["ONNX Runtime"]="OK"
        SUMMARY_DETAIL["ONNX Runtime"]="Installed"
    else
        SUMMARY_STATUS["ONNX Runtime"]="NOT INSTALLED"
        SUMMARY_DETAIL["ONNX Runtime"]="--"
    fi

    # ROCm summary (already checked in GPU section, just set status)
    if cmd_exists rocminfo; then
        SUMMARY_STATUS["ROCm"]="OK"
        SUMMARY_DETAIL["ROCm"]="Installed"
    else
        SUMMARY_STATUS["ROCm"]="NOT INSTALLED"
        SUMMARY_DETAIL["ROCm"]="--"
    fi

    # Build Environment (compilers, cmake, make)
    md "### Build Environment"
    md ""
    md "| Tool | Version | Path |"
    md "|------|---------|------|"

    local compiler_found="false"
    for cc in gcc cc x86_64-conda-linux-gnu-gcc; do
        if cmd_exists "$cc"; then
            local cc_ver cc_path
            cc_ver="$($cc --version 2>/dev/null | head -1)"
            cc_path="$(which "$cc" 2>/dev/null)"
            md "| \`${cc}\` | ${cc_ver} | \`${cc_path}\` |"
            compiler_found="true"
        fi
    done
    for cxx in g++ c++ x86_64-conda-linux-gnu-g++; do
        if cmd_exists "$cxx"; then
            local cxx_ver cxx_path
            cxx_ver="$($cxx --version 2>/dev/null | head -1)"
            cxx_path="$(which "$cxx" 2>/dev/null)"
            md "| \`${cxx}\` | ${cxx_ver} | \`${cxx_path}\` |"
            compiler_found="true"
        fi
    done
    if cmd_exists cmake; then
        local cmake_ver cmake_path
        cmake_ver="$(cmake --version 2>/dev/null | head -1)"
        cmake_path="$(which cmake 2>/dev/null)"
        md "| \`cmake\` | ${cmake_ver} | \`${cmake_path}\` |"
    else
        md "| \`cmake\` | -- | Not found |"
    fi
    if cmd_exists make; then
        local make_ver make_path
        make_ver="$(make --version 2>/dev/null | head -1)"
        make_path="$(which make 2>/dev/null)"
        md "| \`make\` | ${make_ver} | \`${make_path}\` |"
    else
        md "| \`make\` | -- | Not found |"
    fi
    md ""

    if [[ "$compiler_found" == "true" ]]; then
        log_ok "Build tools found"
        SUMMARY_STATUS["Build Tools"]="OK"
        SUMMARY_DETAIL["Build Tools"]="Compiler + cmake available"
    else
        log_warn "No C/C++ compiler found"
        SUMMARY_STATUS["Build Tools"]="NOT FOUND"
        SUMMARY_DETAIL["Build Tools"]="No compiler found"
    fi

    # ONNX Runtime C++ Libraries (distinct from Python packages)
    md "### ONNX Runtime C++ Libraries"
    md ""

    local ort_lib_search_dirs=()
    [[ -n "${ONNXRUNTIME_ROOTDIR:-}" && -d "${ONNXRUNTIME_ROOTDIR}/lib" ]] && ort_lib_search_dirs+=("${ONNXRUNTIME_ROOTDIR}/lib")
    # Check for standard ORT tarball in common locations
    for candidate in /home/*/onnxruntime/onnxruntime-linux-*/lib /opt/onnxruntime/lib /usr/local/lib; do
        for d in $candidate; do
            [[ -d "$d" && -f "$d/libonnxruntime.so" ]] && ort_lib_search_dirs+=("$d")
        done
    done
    # Check CVML ryzen14
    local cvml_ryzen14="${SCRIPT_DIR}/Ryzen-AI-CVML-Library/linux/onnx/ryzen14"
    [[ -d "$cvml_ryzen14" && -f "$cvml_ryzen14/libonnxruntime.so" ]] && ort_lib_search_dirs+=("$cvml_ryzen14")

    local ort_cpp_found="false"
    if [[ ${#ort_lib_search_dirs[@]} -gt 0 ]]; then
        md "| Location | ORT Version (soname) | VitisAI EP |"
        md "|----------|---------------------|------------|"
        for dir in "${ort_lib_search_dirs[@]}"; do
            local soname vitisai_ep
            soname="$(objdump -p "$dir/libonnxruntime.so" 2>/dev/null | grep SONAME | awk '{print $2}' || echo "unknown")"
            if [[ -f "$dir/libonnxruntime_vitisai_ep.so" ]]; then
                vitisai_ep="Present"
            else
                vitisai_ep="Not present"
            fi
            md "| \`${dir}\` | ${soname} | ${vitisai_ep} |"
            ort_cpp_found="true"
        done
        md ""
    else
        md "> No ONNX Runtime C++ libraries found. Set \`ONNXRUNTIME_ROOTDIR\` or install ORT."
        md ""
    fi

    if [[ "$ort_cpp_found" == "true" ]]; then
        SUMMARY_STATUS["ORT C++ Libs"]="OK"
        SUMMARY_DETAIL["ORT C++ Libs"]="Found in ${#ort_lib_search_dirs[@]} location(s)"
    else
        SUMMARY_STATUS["ORT C++ Libs"]="NOT FOUND"
        SUMMARY_DETAIL["ORT C++ Libs"]="--"
    fi

    # CVML Library
    md "### CVML Library (Ryzen AI deployment libs)"
    md ""

    local cvml_base="${SCRIPT_DIR}/Ryzen-AI-CVML-Library"
    if [[ -d "$cvml_ryzen14" ]]; then
        local so_count xclbin_count vaip_config
        so_count="$(ls "$cvml_ryzen14"/*.so* 2>/dev/null | wc -l)"
        xclbin_count="$(ls "$cvml_ryzen14"/*.xclbin 2>/dev/null | wc -l)"
        vaip_config="false"
        [[ -f "$cvml_ryzen14/vaip_config_npu_2_3.json" ]] && vaip_config="true"

        md "| Field | Value |"
        md "|-------|-------|"
        md "| **Path** | \`${cvml_ryzen14}\` |"
        md "| **Shared libraries** | ${so_count} .so files |"
        md "| **XCLBIN overlays** | ${xclbin_count} .xclbin files |"
        md "| **vaip_config_npu_2_3.json** | ${vaip_config} |"

        # Check for key libraries
        for lib in libonnxruntime.so libvaip-core.so libxcompiler-core-without-symbol.so \
                   libonnxruntime_vitisai_ep.so libvart-cpu-runner.so.3; do
            local present="false"
            [[ -f "$cvml_ryzen14/$lib" || -L "$cvml_ryzen14/$lib" ]] && present="true"
            md "| **${lib}** | ${present} |"
        done
        md ""

        log_ok "CVML ryzen14: ${so_count} libs"
        SUMMARY_STATUS["CVML Library"]="OK"
        SUMMARY_DETAIL["CVML Library"]="${so_count} libs in ryzen14/"
    elif [[ -d "$cvml_base" ]]; then
        md "> CVML base directory found but \`linux/onnx/ryzen14/\` subdirectory missing."
        md ""
        log_warn "CVML found but ryzen14 missing"
        SUMMARY_STATUS["CVML Library"]="WARN"
        SUMMARY_DETAIL["CVML Library"]="Base dir only, ryzen14/ missing"
    else
        md "> CVML Library not found at \`${cvml_base}\`."
        md ""
        log_warn "CVML Library not found"
        SUMMARY_STATUS["CVML Library"]="NOT FOUND"
        SUMMARY_DETAIL["CVML Library"]="--"
    fi

    # VitisAI / ORT Environment Variables
    md "### VitisAI / ORT Environment Variables"
    md ""
    md "| Variable | Value |"
    md "|----------|-------|"

    local env_vars=(
        "ONNXRUNTIME_ROOTDIR"
        "OVERRIDE_VITISAI_ORT_MODEL_PATH"
        "VITISAI_ORT_CONFIG_FILE"
        "XLNX_VART_FIRMWARE"
        "RYZEN_AI_INSTALLATION_PATH"
        "VAIP_CONFIG_HOME"
        "ORT_VITISAI_ALL_PROVIDER_OPTIONS"
        "HSA_OVERRIDE_GFX_VERSION"
        "GPU_MAX_HEAP_SIZE"
        "HIP_HIDDEN_FREE_MEM"
        "GPU_SINGLE_ALLOC_PERCENT"
        "MIOPEN_FIND_MODE"
        "OLLAMA_FLASH_ATTENTION"
        "OLLAMA_NO_MMAP"
        "LD_LIBRARY_PATH"
        "CONDA_PREFIX"
        "CONDA_DEFAULT_ENV"
    )

    for var in "${env_vars[@]}"; do
        local val="${!var:-}"
        if [[ -n "$val" ]]; then
            # Truncate long values (LD_LIBRARY_PATH can be huge)
            if [[ ${#val} -gt 120 ]]; then
                val="${val:0:117}..."
            fi
            md "| \`${var}\` | \`${val}\` |"
        else
            md "| \`${var}\` | *not set* |"
        fi
    done
    md ""

    # Runtime Dependencies (needed by CVML VitisAI EP)
    md "### Runtime Dependencies (VitisAI EP)"
    md ""
    md "These shared libraries are required at runtime when using CVML's VitisAI-enabled ONNX Runtime."
    md ""
    md "| Library | Required By | Found |"
    md "|---------|-------------|-------|"

    local runtime_deps=(
        "libpython3.10.so.1.0:VitisAI EP (CVML)"
        "libboost_filesystem.so:VitisAI EP (CVML)"
        "libgomp.so.1:ORT parallel execution"
        "libstdc++.so.6:C++ runtime"
    )

    local deps_ok="true"
    for entry in "${runtime_deps[@]}"; do
        local lib="${entry%%:*}"
        local needed_by="${entry##*:}"
        local found_path=""

        # Search ldconfig cache (exact match first, then glob)
        found_path="$(ldconfig -p 2>/dev/null | grep -m1 "$lib" | awk '{print $NF}' || true)"

        # Search LD_LIBRARY_PATH
        if [[ -z "$found_path" && -n "${LD_LIBRARY_PATH:-}" ]]; then
            local IFS=:
            for ld_dir in $LD_LIBRARY_PATH; do
                local match
                match="$(ls "$ld_dir"/${lib}* 2>/dev/null | head -1 || true)"
                if [[ -n "$match" ]]; then
                    found_path="$match"
                    break
                fi
            done
            unset IFS
        fi

        # Search current conda env
        if [[ -z "$found_path" && -n "${CONDA_PREFIX:-}" ]]; then
            local match
            match="$(ls "${CONDA_PREFIX}/lib"/${lib}* 2>/dev/null | head -1 || true)"
            [[ -n "$match" ]] && found_path="$match"
        fi

        # Search ALL conda envs
        if [[ -z "$found_path" ]]; then
            for env_dir in ~/miniforge3/envs/*/lib ~/miniconda3/envs/*/lib ~/anaconda3/envs/*/lib; do
                for d in $env_dir; do
                    [[ -d "$d" ]] || continue
                    local match
                    match="$(ls "$d"/${lib}* 2>/dev/null | head -1 || true)"
                    if [[ -n "$match" ]]; then
                        found_path="$match"
                        break 2
                    fi
                done
            done
        fi

        if [[ -n "$found_path" ]]; then
            md "| \`${lib}\` | ${needed_by} | \`${found_path}\` |"
        else
            md "| \`${lib}\` | ${needed_by} | **NOT FOUND** |"
            deps_ok="false"
        fi
    done
    md ""

    # Detailed boost_filesystem availability across all locations
    md "#### boost_filesystem Availability"
    md ""
    local boost_found_anywhere="false"
    local boost_table=""

    # Check ldconfig
    local ldconfig_boost
    ldconfig_boost="$(ldconfig -p 2>/dev/null | grep 'libboost_filesystem' || true)"
    while IFS= read -r line; do
        [[ -z "$line" ]] && continue
        local bpath bver
        bpath="$(echo "$line" | awk '{print $NF}')"
        bver="$(basename "$bpath" | grep -oP '\.so\.\K[0-9.]+' || echo "unknown")"
        boost_table+="| system (ldconfig) | ${bver} | \`${bpath}\` |"$'\n'
        boost_found_anywhere="true"
    done <<< "$ldconfig_boost"

    # Check all conda envs
    for env_dir in ~/miniforge3/envs/*/lib ~/miniconda3/envs/*/lib ~/anaconda3/envs/*/lib; do
        for d in $env_dir; do
            [[ -d "$d" ]] || continue
            local boost_files
            boost_files="$(ls "$d"/libboost_filesystem.so.* 2>/dev/null || true)"
            while IFS= read -r bf; do
                [[ -z "$bf" ]] && continue
                local bver env_name
                bver="$(basename "$bf" | grep -oP '\.so\.\K[0-9.]+' || echo "unknown")"
                env_name="$(basename "$(dirname "$(dirname "$bf")")")"
                boost_table+="| conda (${env_name}) | ${bver} | \`${bf}\` |"$'\n'
                boost_found_anywhere="true"
            done <<< "$boost_files"
        done
    done

    if [[ "$boost_found_anywhere" == "true" ]]; then
        md "| Location | Version | Path |"
        md "|----------|---------|------|"
        md "$boost_table"
    else
        md "> No libboost_filesystem found on system or in conda envs."
        md ""
    fi

    # Python 3.10 and its .so location
    local py310_path=""
    py310_path="$(which python3.10 2>/dev/null || true)"
    if [[ -z "$py310_path" ]]; then
        for env_dir in ~/miniforge3/envs/*/bin ~/miniconda3/envs/*/bin ~/anaconda3/envs/*/bin; do
            for d in $env_dir; do
                [[ -x "$d/python3.10" ]] && py310_path="$d/python3.10" && break 2
            done
        done
    fi
    if [[ -n "$py310_path" ]]; then
        local py310_lib_dir
        py310_lib_dir="$(dirname "$(dirname "$py310_path")")/lib"
        local py310_so=""
        [[ -f "$py310_lib_dir/libpython3.10.so.1.0" ]] && py310_so="$py310_lib_dir/libpython3.10.so.1.0"
        md "> Python 3.10: found at \`${py310_path}\`"
        if [[ -n "$py310_so" ]]; then
            md "> libpython3.10.so.1.0: \`${py310_so}\`"
            md "> To make available: \`export LD_LIBRARY_PATH=${py310_lib_dir}:\$LD_LIBRARY_PATH\`"
        else
            md "> libpython3.10.so.1.0: **NOT FOUND** in \`${py310_lib_dir}\`"
        fi
        md ""
    else
        md "> Python 3.10: **not found** (required by CVML VitisAI EP — install via \`conda create -n py310 python=3.10\`)"
        md ""
    fi

    # Conda Environments
    if cmd_exists conda; then
        md "### Conda Environments"
        md ""
        local conda_envs
        conda_envs="$(conda env list --json 2>/dev/null | python3 -c "
import sys, json
data = json.load(sys.stdin)
for e in data.get('envs', []):
    print(e)
" 2>/dev/null || true)"

        if [[ -n "$conda_envs" ]]; then
            md "| Environment | Python |"
            md "|-------------|--------|"
            while IFS= read -r env_path; do
                local env_name py_ver_env
                env_name="$(basename "$env_path")"
                [[ "$env_path" == *"/miniforge3" || "$env_path" == *"/miniconda3" || "$env_path" == *"/anaconda3" ]] && env_name="(base)"
                py_ver_env="$("$env_path/bin/python3" --version 2>/dev/null | awk '{print $2}' || echo "N/A")"
                md "| ${env_name} | ${py_ver_env} |"
            done <<< "$conda_envs"
            md ""
        fi
    fi
}

# ---------------------------------------------------------------------------
# Section: Kubernetes Infrastructure
# ---------------------------------------------------------------------------

section_kubernetes() {
    log_section "Kubernetes Infrastructure"

    md "---"
    md ""
    md "## Kubernetes Infrastructure"
    md ""

    # Check core tools
    md "### Tools"
    md ""
    md "| Tool | Version | Path |"
    md "|------|---------|------|"

    local k8s_ready="false"
    for tool in kubectl helm kubeadm kubelet; do
        if cmd_exists "$tool"; then
            local tool_ver tool_path
            case "$tool" in
                kubectl) tool_ver="$(kubectl version --client -o json 2>/dev/null | python3 -c "import sys,json; print(json.load(sys.stdin)['clientVersion']['gitVersion'])" 2>/dev/null || kubectl version --client 2>/dev/null | head -1 || echo "unknown")" ;;
                helm)    tool_ver="$(helm version --short 2>/dev/null || echo "unknown")" ;;
                kubeadm) tool_ver="$(kubeadm version -o short 2>/dev/null || echo "unknown")" ;;
                kubelet) tool_ver="$(kubelet --version 2>/dev/null | awk '{print $2}' || echo "unknown")" ;;
            esac
            tool_path="$(which "$tool" 2>/dev/null)"
            md "| \`${tool}\` | ${tool_ver} | \`${tool_path}\` |"
            [[ "$tool" == "kubectl" ]] && k8s_ready="true"
        else
            md "| \`${tool}\` | -- | Not found |"
        fi
    done
    md ""

    # Container runtime
    md "### Container Runtime"
    md ""
    md "| Field | Value |"
    md "|-------|-------|"

    if cmd_exists containerd; then
        local ctr_ver
        ctr_ver="$(containerd --version 2>/dev/null | awk '{print $3}' || echo "unknown")"
        md "| **containerd** | ${ctr_ver} |"
        local ctr_status
        ctr_status="$(systemctl is-active containerd 2>/dev/null || echo "unknown")"
        md "| **Status** | ${ctr_status} |"
    elif cmd_exists crio; then
        local crio_ver
        crio_ver="$(crio --version 2>/dev/null | head -1 || echo "unknown")"
        md "| **CRI-O** | ${crio_ver} |"
    else
        md "| **Runtime** | Not detected |"
    fi

    if cmd_exists podman; then
        local podman_ver
        podman_ver="$(podman --version 2>/dev/null | awk '{print $NF}' || echo "unknown")"
        md "| **podman** | ${podman_ver} |"
    fi
    md ""

    # Cluster status (only if kubectl works)
    if [[ "$k8s_ready" == "true" ]] && kubectl cluster-info &>/dev/null; then
        md "### Cluster Status"
        md ""

        # Node info
        local node_info
        node_info="$(kubectl get nodes -o wide --no-headers 2>/dev/null || true)"
        if [[ -n "$node_info" ]]; then
            md "| Node | Status | Roles | Version | Kernel | Container Runtime |"
            md "|------|--------|-------|---------|--------|-------------------|"
            local node_table
            node_table="$(kubectl get nodes -o wide --no-headers 2>/dev/null | awk '{
                name=$1; status=$2; roles=$3; ver=$5; kernel=$(NF-1); crt=$NF
                printf "| %s | %s | %s | %s | %s | %s |\n", name, status, roles, ver, kernel, crt
            }' || true)"
            [[ -n "$node_table" ]] && md "$node_table"
            md ""
        fi

        # Namespace pod counts
        md "### Workload Summary"
        md ""
        md "| Namespace | Running | Pending | Failed | Total |"
        md "|-----------|---------|---------|--------|-------|"

        local ns_list
        ns_list="$(kubectl get pods --all-namespaces --no-headers 2>/dev/null | awk '{print $1}' | sort -u || true)"
        while IFS= read -r ns; do
            [[ -z "$ns" ]] && continue
            local pod_lines
            pod_lines="$(kubectl get pods -n "$ns" --no-headers 2>/dev/null || true)"
            local running pending failed total
            running=$(echo "$pod_lines" | grep -c "Running" || true)
            pending=$(echo "$pod_lines" | grep -c "Pending" || true)
            failed=$(echo "$pod_lines" | grep -cE "Error|CrashLoop|Failed" || true)
            total=$(echo "$pod_lines" | grep -c . || true)
            md "| ${ns} | ${running} | ${pending} | ${failed} | ${total} |"
        done <<< "$ns_list"
        md ""

        # GPU/NPU device passthrough pods (privileged pods with device mounts)
        md "### Hardware-Accelerated Pods"
        md ""
        local hw_pods
        hw_pods="$(kubectl get pods --all-namespaces -o json 2>/dev/null | python3 -c "
import sys, json
data = json.load(sys.stdin)
results = []
for item in data.get('items', []):
    ns = item['metadata']['namespace']
    name = item['metadata']['name']
    phase = item.get('status', {}).get('phase', 'Unknown')
    devices = set()
    for c in item.get('spec', {}).get('containers', []):
        for vm in c.get('volumeMounts', []):
            mp = vm.get('mountPath', '')
            if '/dev/dri' in mp: devices.add('GPU')
            if '/dev/kfd' in mp: devices.add('ROCm')
            if '/dev/accel' in mp: devices.add('NPU')
    if devices:
        results.append((ns, name, phase, '+'.join(sorted(devices))))
for ns, name, phase, devs in results:
    print(f'| {ns} | {name} | {phase} | {devs} |')
" 2>/dev/null || true)"

        if [[ -n "$hw_pods" ]]; then
            md "| Namespace | Pod | Phase | Devices |"
            md "|-----------|-----|-------|---------|"
            md "$hw_pods"
        else
            md "> No pods with hardware device mounts detected."
        fi
        md ""

        # Resource Policies
        md "### Resource Policies"
        md ""

        # PriorityClasses (custom, non-system)
        local pc_table
        pc_table="$(kubectl get priorityclasses -o json 2>/dev/null | python3 -c "
import sys, json
data = json.load(sys.stdin)
results = []
for item in data.get('items', []):
    name = item['metadata']['name']
    if name in ('system-cluster-critical', 'system-node-critical'):
        continue
    value = item.get('value', 0)
    preempt = item.get('preemptionPolicy', 'PreemptLowerPriority')
    default = item.get('globalDefault', False)
    results.append(f'| {name} | {value} | {preempt} | {default} |')
for r in results:
    print(r)
" 2>/dev/null || true)"

        if [[ -n "$pc_table" ]]; then
            md "#### PriorityClasses (custom)"
            md ""
            md "| Name | Value | Preemption | Global Default |"
            md "|------|-------|-----------|----------------|"
            md "$pc_table"
            md ""
        else
            md "> No custom PriorityClasses defined."
            md ""
        fi

        # ResourceQuotas
        local rq_table
        rq_table="$(kubectl get resourcequotas --all-namespaces -o json 2>/dev/null | python3 -c "
import sys, json
data = json.load(sys.stdin)
for item in data.get('items', []):
    ns = item['metadata']['namespace']
    name = item['metadata']['name']
    hard = item.get('spec', {}).get('hard', {})
    limits_str = ', '.join(f'{k}={v}' for k, v in hard.items())
    print(f'| {ns} | {name} | {limits_str} |')
" 2>/dev/null || true)"

        if [[ -n "$rq_table" ]]; then
            md "#### ResourceQuotas"
            md ""
            md "| Namespace | Name | Hard Limits |"
            md "|-----------|------|-------------|"
            md "$rq_table"
            md ""
        else
            md "> No ResourceQuotas defined in any namespace."
            md ""
        fi

        # LimitRanges
        local lr_table
        lr_table="$(kubectl get limitranges --all-namespaces -o json 2>/dev/null | python3 -c "
import sys, json
data = json.load(sys.stdin)
for item in data.get('items', []):
    ns = item['metadata']['namespace']
    name = item['metadata']['name']
    for limit in item.get('spec', {}).get('limits', []):
        ltype = limit.get('type', 'Container')
        default = ', '.join(f'{k}={v}' for k, v in limit.get('default', {}).items()) or 'none'
        default_req = ', '.join(f'{k}={v}' for k, v in limit.get('defaultRequest', {}).items()) or 'none'
        print(f'| {ns} | {name} | {ltype} | {default} | {default_req} |')
" 2>/dev/null || true)"

        if [[ -n "$lr_table" ]]; then
            md "#### LimitRanges"
            md ""
            md "| Namespace | Name | Type | Default Limit | Default Request |"
            md "|-----------|------|------|---------------|-----------------|"
            md "$lr_table"
            md ""
        else
            md "> No LimitRanges defined in any namespace."
            md ""
        fi

        # Custom node labels (accelerator/*, topology/*)
        md "#### Node Labels (accelerator/topology)"
        md ""
        local node_labels
        node_labels="$(kubectl get nodes -o json 2>/dev/null | python3 -c "
import sys, json
data = json.load(sys.stdin)
for item in data.get('items', []):
    name = item['metadata']['name']
    labels = item['metadata'].get('labels', {})
    custom = {k: v for k, v in labels.items() if k.startswith(('accelerator/', 'topology/'))}
    if custom:
        for k, v in custom.items():
            print(f'| {name} | {k} | {v} |')
    else:
        print(f'| {name} | (none) | -- |')
" 2>/dev/null || true)"

        if [[ -n "$node_labels" ]]; then
            md "| Node | Label | Value |"
            md "|------|-------|-------|"
            md "$node_labels"
        else
            md "> No custom accelerator/topology labels on nodes."
        fi
        md ""

        log_ok "Kubernetes cluster accessible"
        SUMMARY_STATUS["Kubernetes"]="OK"
        SUMMARY_DETAIL["Kubernetes"]="Cluster accessible"
    elif [[ "$k8s_ready" == "true" ]]; then
        md "> kubectl found but cluster is not accessible."
        md ""
        log_warn "kubectl found but cluster unreachable"
        SUMMARY_STATUS["Kubernetes"]="WARN"
        SUMMARY_DETAIL["Kubernetes"]="kubectl found, cluster unreachable"
    else
        md "> kubectl not found. Kubernetes status cannot be checked."
        md ""
        log_warn "kubectl not found"
        SUMMARY_STATUS["Kubernetes"]="NOT FOUND"
        SUMMARY_DETAIL["Kubernetes"]="kubectl not found"
    fi
}

# ---------------------------------------------------------------------------
# Section: Summary
# ---------------------------------------------------------------------------

section_summary() {
    log_section "Generating summary"

    md "---"
    md ""
    md "## Summary"
    md ""
    md "| Component | Status | Details |"
    md "|-----------|--------|---------|"

    # Ordered list of components
    local components=(
        "Kernel"
        "CPU"
        "Memory"
        "Disk Space"
        "GPU"
        "VAAPI"
        "NPU"
        "NPU Device Node"
        "NPU Firmware"
        "XRT"
        "VAIP Passes"
        "Build Tools"
        "ORT C++ Libs"
        "ONNX Runtime"
        "CVML Library"
        "ROCm"
        "Ryzen AI SDK"
        "Kubernetes"
    )

    for comp in "${components[@]}"; do
        local status="${SUMMARY_STATUS[$comp]:-UNKNOWN}"
        local detail="${SUMMARY_DETAIL[$comp]:-}"
        md "| ${comp} | ${status} | ${detail} |"

        # Terminal output
        case "$status" in
            OK)             log_ok "${comp}: ${detail}" ;;
            WARN)           log_warn "${comp}: ${detail}" ;;
            NOT\ INSTALLED) log_fail "${comp}: not installed" ;;
            NOT\ CONFIGURED) log_warn "${comp}: ${detail}" ;;
            NOT\ FOUND)     log_fail "${comp}: not found" ;;
            BLOCKED)        log_fail "${comp}: ${detail}" ;;
            ERROR)          log_fail "${comp}: ${detail}" ;;
            *)              log_warn "${comp}: ${status}" ;;
        esac
    done

    md ""
    md "---"
    md ""
    md "*Generated by [RyzenAI-SW](https://github.com/amd/RyzenAI-SW) system report utility.*"
}

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

main() {
    parse_args "$@"

    printf "\n${BOLD}${CYAN}Ryzen AI System Report Generator v${REPORT_VERSION}${RESET}\n"
    printf "Output: %s\n\n" "$OUTPUT_FILE"

    init_sudo

    printf "\n"

    section_header
    section_system_overview
    section_cpu
    section_memory
    section_gpu
    section_npu
    section_software
    section_kubernetes
    section_summary

    printf "%s" "$REPORT" > "$OUTPUT_FILE"

    printf "\n${BOLD}${GREEN}Report written to: %s${RESET}\n" "$OUTPUT_FILE"
}

main "$@"
